controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api:
    resource:
        path: ../src/Api/Controller/
        namespace: App\Api\Controller
    prefix: api/
    type: attribute
